/* Synced from @gem/design — do not edit here; edit in the monorepo. */
/**
 * @gem/design — shared Tailwind preset (the eccuity / v2 design language).
 *
 * Every project gets the brand by spreading this preset:
 *   // tailwind.config.{js,ts}
 *   module.exports = { presets: [require('@gem/design/preset')], content: [...] }
 *
 * It carries the palette, the semantic CSS-variable tokens (light + dark),
 * radius, shadows, fonts, animations, and the eccuity component/utility layer.
 * Keep this CommonJS + self-contained so Tailwind's config loader can require it
 * with no build step, from any repo.
 */
const animate = require('tailwindcss-animate');
const typography = require('@tailwindcss/typography');

const gemBlack = {
  25: '#E7DCDA',
  50: '#F3EEED',
  75: '#B9ADB4',
  100: '#939393',
  200: '#7D757D',
  300: '#3F3F42',
  400: '#2C2C2F',
  500: '#272727',
  600: '#242424',
  700: '#202021',
  800: '#1E1E1E',
  900: '#1B1B1B',
  1000: '#1A1A1A',
  DEFAULT: '#3F3E3F',
};

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  safelist: ['bg-gem-stock', 'bg-gem-etf', 'bg-gem-crypto', 'bg-gem-cash', 'bg-gem-stock/10', 'bg-gem-etf/10', 'bg-gem-crypto/10', 'bg-gem-cash/10'],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        surface: 'var(--surface)',
        'surface-raised': 'var(--surface-raised)',
        'subtle-border': 'var(--subtle-border)',
        'hover-surface': 'var(--hover-surface)',
        'card-muted': 'var(--card-muted)',
        'subtle-foreground': 'var(--subtle-foreground)',
        'secondary-foreground-muted': 'var(--secondary-foreground-muted)',
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
        },
        'gem-black': gemBlack,
        'gem-purple': {
          DEFAULT: '#352351',
          hover: '#5D4F74',
        },
        'gem-coral': '#ff5748',
        'expense-red': '#FF5752',
        'gem-pink': {
          DEFAULT: '#FF6B9D',
          light: '#F58F8F',
        },
        'gem-gold': '#FDB71A',
        'gem-teal': '#08B86E',
        'gem-gray': {
          DEFAULT: '#9CA3AF',
        },
        'gem-purple-dark': {
          DEFAULT: '#4a3f5c',
          hover: '#5a4f6c',
          darker: '#2a1d3f',
        },
        'gem-purple-light': {
          DEFAULT: '#8b7aa8',
          100: '#E1D3F6',
        },
        'gem-beige': {
          DEFAULT: '#F8F5F0',
          light: '#FED7AA',
        },
        'gem-green': {
          DEFAULT: '#64CEA2',
          100: '#92FFD1',
          700: '#285240',
        },
        'gem-orange': {
          DEFAULT: '#ED8B51',
        },
        'gem-stock': '#1588E0',
        'gem-stock-hover': '#6B9BD8',
        'gem-etf': '#9333EA',
        'gem-etf-hover': '#8B7BAE',
        'gem-crypto': '#EAB308',
        'gem-crypto-hover': '#D4B85A',
        'gem-cash': '#22C55E',
        'ecc-light': {
          100: '#F9F7F6',
          300: '#B9ADB4',
        },
        'eccuity-purple': {
          100: '#5D4F74',
          200: '#6845A1',
          300: '#352351',
        },
        'eccuity-light': {
          100: '#F9F7F6',
          200: '#F3EEED',
          300: '#E7DCDA',
          400: '#B9ADB4',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar-background)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
      },
      boxShadow: {
        sticky: '2px 0 4px -2px rgba(0,0,0,0.1)',
        'sticky-dark': '2px 0 4px -2px rgba(0,0,0,0.3)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        typing: {
          '0%': { transform: 'translateY(0px)' },
          '28%': { transform: 'translateY(-7px)' },
          '44%': { transform: 'translateY(0px)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        typing: 'typing 1.8s ease-in-out infinite',
      },
      fontFamily: {
        sans: ['Libre Franklin', 'sans-serif'],
        space: ['"Space Grotesk"'],
      },
    },
  },
  plugins: [
    animate,
    typography,
    function ({ addBase }) {
      addBase({
        ':root': {
          '--background': 'hsl(0, 0%, 100%)',
          '--foreground': '#1a1a1a' /* gem-black-1000 */,
          '--muted': '#f3eeed' /* gem-black-50 */,
          '--muted-foreground': '#b9adb4' /* gem-black-75 */,
          '--popover': 'hsl(0, 0%, 100%)',
          '--popover-foreground': '#352351' /* gem-purple */,
          '--card': 'hsl(0, 0%, 100%)',
          '--card-foreground': '#352351' /* gem-purple */,
          '--border': '#7d757d' /* gem-black-200 */,
          '--input': '#7d757d' /* gem-black-200 */,
          '--primary': '#352351' /* gem-purple */,
          '--primary-foreground': 'hsl(0, 0%, 100%)',
          '--secondary': '#ff5748' /* gem-coral */,
          '--secondary-foreground': 'hsl(0, 0%, 100%)',
          '--accent': 'hsl(180, 25%, 88%)' /* Light mint/teal accent */,
          '--accent-foreground': '#352351' /* gem-purple */,
          '--destructive': '#ff5748' /* gem-coral */,
          '--destructive-foreground': 'hsl(0, 0%, 100%)',
          '--ring': '#352351' /* gem-purple */,
          '--radius': '0.75rem',
          '--subtle-border': '#e5e7eb' /* gray-200 */,
          '--subtle-foreground': '#6b7280' /* gray-500 */,
          '--secondary-foreground-muted': '#4b5563' /* gray-600 */,
          '--hover-surface': '#f9fafb' /* gray-50 */,
          '--surface': '#f9fafb' /* gray-50 */,
          '--surface-raised': 'hsl(0, 0%, 100%)' /* white */,
          '--card-muted': '#f3f4f6' /* gray-100 */,
          '--neutral-25': '#e7dcda' /* gem-black-25 */,
          '--neutral-50': '#f3eeed' /* gem-black-50 */,
          '--neutral-75': '#b9adb4' /* gem-black-75 */,
          '--neutral-100': '#939393' /* gem-black-100 */,
          '--neutral-200': '#7d757d' /* gem-black-200 */,
          '--neutral-300': '#3f3f42' /* gem-black-300 */,
          '--neutral-400': '#2c2c2f' /* gem-black-400 */,
          '--neutral-500': '#272727' /* gem-black-500 */,
          '--neutral-600': '#242424' /* gem-black-600 */,
          '--neutral-700': '#202021' /* gem-black-700 */,
          '--neutral-800': '#1e1e1e' /* gem-black-800 */,
          '--neutral-900': '#1b1b1b' /* gem-black-900 */,
          '--neutral-950': '#1a1a1a' /* gem-black-1000 */,
          '--chart-1': 'hsl(145, 85%, 50%)',
          '--chart-2': 'hsl(2, 100%, 66%)',
          '--chart-3': 'hsl(262, 65%, 55%)',
          '--chart-4': 'hsl(200, 100%, 55%)',
          '--chart-5': 'hsl(45, 100%, 50%)',
          '--chart-6': 'hsl(175, 70%, 45%)',
          '--chart-7': 'hsl(270, 70%, 65%)',
          '--chart-8': 'hsl(25, 90%, 55%)',
          '--chart-9': 'hsl(340, 80%, 60%)',
          '--chart-10': 'hsl(120, 60%, 40%)',
          '--chart-11': 'hsl(190, 85%, 50%)',
          '--chart-12': 'hsl(290, 75%, 60%)',
        },
        '.dark': {
          '--background': '#1a1a1a' /* gem-black-1000 */,
          '--foreground': 'hsl(0, 0%, 98%)',
          '--muted': '#202021' /* gem-black-700 */,
          '--muted-foreground': '#b9adb4' /* gem-black-75 */,
          '--popover': '#1a1a1a' /* gem-black-1000 */,
          '--popover-foreground': 'hsl(0, 0%, 98%)',
          '--card': '#202021' /* gem-black-700 */,
          '--card-foreground': 'hsl(0, 0%, 98%)',
          '--border': '#2c2c2f' /* gem-black-400 */,
          '--input': '#2c2c2f' /* gem-black-400 */,
          '--primary': '#5d4f74' /* gem-purple-hover */,
          '--primary-foreground': 'hsl(0, 0%, 100%)',
          '--secondary': '#ff5748' /* gem-coral */,
          '--secondary-foreground': 'hsl(0, 0%, 100%)',
          '--accent': 'hsl(180, 25%, 20%)' /* Darker teal accent */,
          '--accent-foreground': 'hsl(0, 0%, 98%)',
          '--destructive': '#ff5748' /* gem-coral */,
          '--destructive-foreground': 'hsl(0, 0%, 100%)',
          '--ring': '#5d4f74' /* gem-purple-hover */,
          '--radius': '0.75rem',
          '--subtle-border': '#202021' /* gem-black-700 */,
          '--subtle-foreground': '#9ca3af' /* gray-400 */,
          '--secondary-foreground-muted': '#9ca3af' /* gray-400 */,
          '--hover-surface': '#1e1e1e' /* gem-black-800 */,
          '--surface': '#1a1a1a' /* gem-black-1000 */,
          '--surface-raised': '#202021' /* gem-black-700 */,
          '--card-muted': gemBlack[600],
          '--chart-1': 'hsl(145, 85%, 60%)',
          '--chart-2': 'hsl(2, 100%, 74%)',
          '--chart-3': 'hsl(262, 65%, 65%)',
          '--chart-4': 'hsl(200, 100%, 65%)',
          '--chart-5': 'hsl(45, 100%, 65%)',
          '--chart-6': 'hsl(175, 70%, 55%)',
          '--chart-7': 'hsl(270, 70%, 75%)',
          '--chart-8': 'hsl(25, 90%, 65%)',
          '--chart-9': 'hsl(340, 80%, 70%)',
          '--chart-10': 'hsl(120, 60%, 50%)',
          '--chart-11': 'hsl(190, 85%, 60%)',
          '--chart-12': 'hsl(290, 75%, 70%)',
        },
        body: {
          backgroundColor: 'var(--background)',
          color: 'var(--foreground)',
          fontFamily: "'Libre Franklin', system-ui, sans-serif",
          WebkitFontSmoothing: 'antialiased',
          MozOsxFontSmoothing: 'grayscale',
        },
        '::-webkit-scrollbar': { width: '6px', height: '6px' },
        '::-webkit-scrollbar-track': { background: 'var(--muted)' },
        '::-webkit-scrollbar-thumb': { background: 'var(--muted-foreground)', borderRadius: '3px' },
        '::-webkit-scrollbar-thumb:hover': { background: 'var(--foreground)' },
      });
    },
    function ({ addComponents, theme }) {
      addComponents({
        '.btn-eccuity-primary': {
          backgroundColor: 'var(--primary)',
          color: 'var(--primary-foreground)',
          transition: 'colors',
          '&:hover': { backgroundColor: 'color-mix(in srgb, var(--primary) 90%, transparent)' },
        },
        '.btn-eccuity-secondary': {
          backgroundColor: 'var(--secondary)',
          color: 'var(--secondary-foreground)',
          transition: 'colors',
          '&:hover': { backgroundColor: 'color-mix(in srgb, var(--secondary) 90%, transparent)' },
        },
        '.card-dashboard': {
          backgroundColor: 'var(--card)',
          borderColor: 'var(--border)',
          borderRadius: '0.75rem',
          border: '1px solid',
          boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        },
        '.metric-positive': { color: 'var(--secondary)' },
        '.metric-negative': { color: 'var(--destructive)' },
        '.metric-neutral': { color: 'var(--muted-foreground)' },
        '.progress-high': { backgroundColor: 'var(--secondary)' },
        '.progress-medium': { backgroundColor: theme('colors.yellow.500') },
        '.progress-low': { backgroundColor: 'var(--destructive)' },
        '.status-planning': { backgroundColor: theme('colors.blue.100'), color: theme('colors.blue.800') },
        '.status-in-progress': { backgroundColor: theme('colors.yellow.100'), color: theme('colors.yellow.800') },
        '.status-on-track': { backgroundColor: theme('colors.green.100'), color: theme('colors.green.800') },
        '.status-completed': { color: 'var(--secondary)', backgroundColor: 'color-mix(in srgb, var(--secondary) 10%, transparent)' },
      });
    },
    function ({ addUtilities, theme }) {
      addUtilities({
        '.animate-slide-up': { animation: 'slideUp 0.3s ease-out' },
        '.animate-fade-in': { animation: 'fadeIn 0.3s ease-out' },
        '.scrollbar-hide': {
          '-ms-overflow-style': 'none',
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': { display: 'none' },
        },
        '.text-financial-positive': { color: 'var(--secondary)', fontWeight: theme('fontWeight.semibold') },
        '.text-financial-negative': { color: 'var(--destructive)', fontWeight: theme('fontWeight.semibold') },
        '.text-financial-neutral': { color: 'var(--muted-foreground)' },
        '.container-dashboard': {
          marginLeft: 'auto',
          marginRight: 'auto',
          maxWidth: theme('maxWidth.7xl'),
          paddingLeft: theme('spacing.4'),
          paddingRight: theme('spacing.4'),
          '@media (min-width: 640px)': { paddingLeft: theme('spacing.6'), paddingRight: theme('spacing.6') },
          '@media (min-width: 1024px)': { paddingLeft: theme('spacing.8'), paddingRight: theme('spacing.8') },
        },
        '.focus-eccuity': {
          '&:focus': { outline: 'none', 'ring-width': '2px', 'ring-offset-width': '2px', 'ring-color': 'var(--primary)' },
        },
        '.form-field-error': { color: 'var(--destructive)', marginTop: theme('spacing.1'), fontSize: theme('fontSize.sm') },
        '.form-input-error': { borderColor: 'var(--destructive)', '&:focus': { 'ring-color': 'var(--destructive)' } },
        '.grid-responsive': {
          '@media (max-width: 640px)': { 'grid-template-columns': 'repeat(1, minmax(0, 1fr))' },
          '@media (min-width: 640px) and (max-width: 1024px)': { 'grid-template-columns': 'repeat(2, minmax(0, 1fr))' },
          '@media (min-width: 1024px)': { 'grid-template-columns': 'repeat(4, minmax(0, 1fr))' },
        },
      });
    },
  ],
};
